language: node_js
node_js:
- '5'
sudo: false
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: MWFYwrK+FZ+rkH7TQ56Qsrxn/M80B3FsEKrHYup11zmbg+snBKcQQENZUAHyRZ3UDKHgijMa3RPXoN9kWN5j+WVfPuhLa+ZoQ6d19VzFAI7ZSjd0A3gX09YlpZ5HoH8eMaa4enYR8sg5Heq+YSPzwNVCoK6AmsKYFrYFQuAL1mE=
  on:
    tags: true
    all_branches: true
